# Generated by Django 3.0.3 on 2020-02-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200226_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='original_paper',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
